apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - image: appscode/analytics:0.1.0
          name: analytics
          ports:
            - containerPort: 9844
              name: web
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  ports:
  - port: 9844
    protocol: TCP
    targetPort: web
  selector:
    app: analytics
